Repository Join-Famila/Famila_Server, pull requests merged in 2023-11, with the labels that each got.

#4 코테스트 의존성 추가
  build.gradle.kts
Labels: build

#5 club entity package 이름 변경
  src/main/kotlin/join/famila/club/infrastructure/Category.kt
  src/main/kotlin/join/famila/club/infrastructure/Club.kt
  src/main/kotlin/join/famila/club/infrastructure/Member.kt
  src/main/kotlin/join/famila/club/infrastructure/Picture.kt
  src/main/kotlin/join/famila/club/infrastructure/Post.kt
  src/main/kotlin/join/famila/club/infrastructure/Schedule.kt
  src/main/kotlin/join/famila/club/infrastructure/Tag.kt
Labels: refactor

#7 club name 추가 및 categories id 연관 매핑 삭제
  src/main/kotlin/join/famila/club/infrastructure/Club.kt
Labels: chore

#8 club 생성 테스트 코드 작성
  src/test/kotlin/join/famila/club/service/ClubServiceTest.kt
Labels: test

#12 Club 생성 기능 추가
  src/main/kotlin/join/famila/club/infrastructure/Club.kt
  src/main/kotlin/join/famila/club/infrastructure/ClubRepository.kt
  src/main/kotlin/join/famila/club/infrastructure/Member.kt
  src/main/kotlin/join/famila/club/infrastructure/MemberRepository.kt
  src/main/kotlin/join/famila/club/request/CreateClubRequest.kt
  src/main/kotlin/join/famila/club/service/ClubService.kt
  src/test/kotlin/join/famila/club/service/ClubServiceTest.kt
Labels: feature

#14 Club Controller 구현
  src/main/kotlin/join/famila/club/controller/ClubController.kt
  src/main/kotlin/join/famila/club/response/CategoryResponse.kt
  src/main/kotlin/join/famila/club/response/ClubResponse.kt
  src/main/kotlin/join/famila/club/response/MemberResponse.kt
  src/main/kotlin/join/famila/club/response/PostResponse.kt
  src/main/kotlin/join/famila/club/response/ScheduleResponse.kt
  src/main/kotlin/join/famila/club/service/ClubService.kt
Labels: feature

#15 ddl create 수정 및 flyway dependencies 제거
  build.gradle.kts
  src/main/resources/application.yml
Labels: chore
